### ISSUE TITLE
Redis issue on heruko? I dont think it got removed correctly

### ISSUE THREAD

**Issue by carolynsteeves1** [Ryuk-me/Torrent-Api-py#34]
2022-08-19T16:35:36.663157+00:00 heroku[web.1]: State changed from crashed to starting

2022-08-19T16:35:39.386347+00:00 heroku[web.1]: Starting process with command `gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app`

2022-08-19T16:35:40.641048+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [4] [INFO] Starting gunicorn 20.1.0

2022-08-19T16:35:40.641501+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [4] [INFO] Listening at: http://0.0.0.0:55238 (4)

2022-08-19T16:35:40.641558+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [4] [INFO] Using worker: uvicorn.workers.UvicornWorker

2022-08-19T16:35:40.647742+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [9] [INFO] Booting worker with pid: 9

2022-08-19T16:35:40.743433+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [10] [INFO] Booting worker with pid: 10

2022-08-19T16:35:40.819807+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [11] [INFO] Booting worker with pid: 11

2022-08-19T16:35:40.833925+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [12] [INFO] Booting worker with pid: 12

2022-08-19T16:35:40.963947+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [9] [ERROR] Exception in worker process

2022-08-19T16:35:40.963983+00:00 app[web.1]: Traceback (most recent call last):

2022-08-19T16:35:40.963986+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker

2022-08-19T16:35:40.963987+00:00 app[web.1]:     worker.init_process()

2022-08-19T16:35:40.963987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process

2022-08-19T16:35:40.963988+00:00 app[web.1]:     super(UvicornWorker, self).init_process()

2022-08-19T16:35:40.963988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process

2022-08-19T16:35:40.963988+00:00 app[web.1]:     self.load_wsgi()

2022-08-19T16:35:40.963989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi

2022-08-19T16:35:40.963989+00:00 app[web.1]:     self.wsgi = self.app.wsgi()

2022-08-19T16:35:40.963990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

2022-08-19T16:35:40.963990+00:00 app[web.1]:     self.callable = self.load()

2022-08-19T16:35:40.963990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

2022-08-19T16:35:40.963990+00:00 app[web.1]:     return self.load_wsgiapp()

2022-08-19T16:35:40.963991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

2022-08-19T16:35:40.963991+00:00 app[web.1]:     return util.import_app(self.app_uri)

2022-08-19T16:35:40.963991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app

2022-08-19T16:35:40.963991+00:00 app[web.1]:     mod = importlib.import_module(module)

2022-08-19T16:35:40.963995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module

2022-08-19T16:35:40.963995+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)

2022-08-19T16:35:40.963996+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

2022-08-19T16:35:40.963996+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

2022-08-19T16:35:40.963996+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

2022-08-19T16:35:40.963997+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

2022-08-19T16:35:40.963997+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module

2022-08-19T16:35:40.963997+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

2022-08-19T16:35:40.963997+00:00 app[web.1]:   File "/app/main.py", line 12, in <module>

2022-08-19T16:35:40.963998+00:00 app[web.1]:     from fastapi_cache.backends.redis import RedisBackend

2022-08-19T16:35:40.963998+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi_cache/backends/redis.py", line 3, in <module>

2022-08-19T16:35:40.963998+00:00 app[web.1]:     from redis.asyncio.client import Redis

2022-08-19T16:35:40.963999+00:00 app[web.1]: ModuleNotFoundError: No module named 'redis'

2022-08-19T16:35:40.963999+00:00 app[web.1]: [2022-08-19 16:35:40 +0000] [9] [INFO] Worker exiting (pid: 9)

2022-08-19T16:35:41.146504+00:00 heroku[web.1]: State changed from starting to up

2022-08-19T16:35:41.367131+00:00 app[web.1]: [2022-08-19 16:35:41 +0000] [4] [WARNING] Worker with pid 12 was terminated due to signal 15

2022-08-19T16:35:41.368091+00:00 app[web.1]: [2022-08-19 16:35:41 +0000] [4] [WARNING] Worker with pid 11 was terminated due to signal 15

2022-08-19T16:35:41.368274+00:00 app[web.1]: [2022-08-19 16:35:41 +0000] [4] [WARNING] Worker with pid 10 was terminated due to signal 15

2022-08-19T16:35:41.464592+00:00 app[web.1]: [2022-08-19 16:35:41 +0000] [4] [INFO] Shutting down: Master

2022-08-19T16:35:41.464670+00:00 app[web.1]: [2022-08-19 16:35:41 +0000] [4] [INFO] Reason: Worker failed to boot.

2022-08-19T16:35:41.667960+00:00 heroku[web.1]: Process exited with status 3

2022-08-19T16:35:41.766381+00:00 heroku[web.1]: State changed from up to crashed

**Comment by Ryuk-me** [comment]
@carolynsteeves1 i will look into this and i don't think it is related to redis.
And one more thing heroku will be removing its free dynos feature

**Comment by m1nka** [comment]
i added redis to requirements.txt file and now it works. like [this](https://github.com/m1nka/Torrent-Api-py/blob/main/requirements.txt).
