### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by mjain234** [Ryuk-me/Torrent-Api-py#37]
i am facing an issue while deploying Torrents-Api-py on vps

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from fastapi import FastAPI, Query
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastapi/routing.py", line 21, in <module>
    from fastapi import params
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
    #   |
ImportError: cannot import name dataclass_transform

**Comment by Ryuk-me** [comment]
It's working fine for everyone try cloning again
sorry for late reply been busy.
